# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='projeto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='colaborates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
