# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerenciador', '0002_auto_20171125_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administers', to=settings.AUTH_USER_MODEL)),
                ('contributors', models.ManyToManyField(related_name='contributes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Dependencia',
            new_name='Dependency',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='colaboradores',
        ),
        migrations.RenameField(
            model_name='dependency',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dependency',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='projeto',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.AddField(
            model_name='dependency',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Project'),
            preserve_default=False,
        ),
    ]
