# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_auto_20171126_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='project',
        ),
        migrations.DeleteModel(
            name='Dependency',
        ),
    ]
