# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_auto_20171127_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='functional',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='gerenciador.Project'),
        ),
    ]
