# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_auto_20171110_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='Id',
        ),
    ]
