# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.Usuario'),
        ),
    ]
