# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20171202_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='functional',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. Inform a valid email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
